//
// USER PRESSES START TO BEGIN THE GAME
//
// TIMER STARTS
//
// STEP ONE: 5-LETTER WORD IS RANDOMLY GENERATED
//
// TABLE IS GENERATED
//
// FIRST LETTER OF MYSTERY WORD IS GIVEN
//
// USER ENTERS A GUESS
//
// GAME TAKES USER INPUT (MUST BE 5 LETTER WORD)
//
// GAME CHECKS WHETHER THERE ARE ANY LETTERS THAT MATCH MYSTERY WORD
//
// IF LETTER IS IN CORRECT POSITION (COLOR THIS)
//
// IF LETTER IS IN INCORRECT POSITON (COLOR THIS)
//
// WORD POPULATES TABLE BELOW MYSTERY WORD COLORED CORRECT
//
// GAME KEEPS TRACK OF HOW MANY GUESSES THERE HAVE BEEN
//
// IF WORD HAS BEEN GUESSED CORRECTLY (CELEBRATORY ANIMATION)
//
// STEP ONE BEGINS AGAIN
//
// EITHER USER RUNS OUT OF GUESSES ON A GIVEN WORD OR TIME RUNS OUT
//
// SOME SCORING MECHANISM (GAME DESIGN)
